version: '3.8'

services:
  robot:
    build:
      context: .
      args:
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    environment:
      - JOB_TOKEN=${JOB_TOKEN}
      - ORCHESTRATOR_URL=${ORCHESTRATOR_URL}
